config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:show, :index, :edit, :update,]

  resources :books do
  	resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'

  get 'users/:id/followers' => 'relationships#followers', as: 'followers'
  get 'users/:id/follows' => 'relationships#follows', as: 'follows'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'

  get 'search' => 'search#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #Relationshipも2つに分けているのでclass_nameが使える。
  #foreign_keyは外部キーで「userのid」とforeign_keyが合致するものを持ってこれる。
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  #簡単にフォローしている、されているユーザーを取得できるようにする記述
  #フォローする人(follower)は中間テーブル(Relationshipのfollower)を通じて(through)、フォローされる人(followed)と紐づく
  has_many :following_user,through: :follower,source: :followed
  #フォローされる人(followed) は中間テーブル(Relationshipのfollowed)を通じて(through)、 フォローする人(follower) と紐づく
  has_many :follower_user,through: :followed,source: :follower

#フォロー機能
  def follow(user_id) #ユーザーをフォローする
    follower.create(followed_id: user_id)
  end
  def unfollow(user_id) #ユーザーのフォローを外す
    follower.find_by(followed_id: user_id).destroy
  end
  def following?(user) #フォロー確認を行う
    following_user.include?(user)
  end
#ここまでフォロー機能

#user、book検索機能
  def self.search(search, word)
    if search == "forward_match"
        @users = User.where(['name LIKE ?', "#{word}%"])
    elsif search == "backward_match"
        @users = User.where(['name LIKE ?', "%#{word}"])
    elsif search == "perfect_match"
        @users = User.where(['name LIKE ?', "#{word}"])
    elsif search == "partial_match"
        @users = User.where(['name LIKE ?', "%#{word}%"])
    else
        @users = User.all
    end
  end
#ここまでuser、book検索機能

#住所検索機能
  include JpPrefecture
  jp_prefecture :prefecture_code #prefecture_codeはuserが持っているカラム
  def prefecture_name #postal_codeからprefecture_name(gem JpPrefectureのカラム)に変換するメソッドを用意する
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name::prefecture_name).code
  end
#ここまで住所検索機能

#住所表示機能
 geocoded_by :address
 after_validation :geocode
#上２行でaddressを登録した際にgeocoder(gem)が緯度、経度のカラムにも自動的に値を入れてくれる。
  geocoded_by :address
  def address
    "#{self.prefecture_code}" + "#{self.city}"
  end
#ここまで住所表示機能

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :books

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
  validates :postal_code, presence: true
  validates :city, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update, :edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def index
  	@users = User.all
  	@book = Book.new
    @user = current_user

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end
end
  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end
  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, format:'jpeg', fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th><%= link_to "#{user.follower.count}", follows_path(user.id) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to "#{user.followed.count}", followers_path(user.id) %></th>
		</tr>
</table>

<% if user.id != current_user.id %>
  <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", unfollow_path(user.id), method: :POST,  class: "btn btn-primary" %>
  <% else %>
    <%= link_to "フォローする", follow_path(user.id), method: :POST, class: "btn btn-success" %>
  <% end %>
<% end %>

<div class="row">
	<% if user.id == current_user.id %>
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3>
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<p>error</p>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
      <h2>User info</h2>
      <%= render 'users/profile', user: @user %>
      <!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

      <h2>New book</h2>
      <%= render 'books/newform', book: @book %>

    </div>
    <div class="col-xs-9">

      <h2>Users</h2>
      <!--users一覧 -->
      <table class="table">
	    <thead>
		  <tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		  </tr>
	    </thead>

	    <tbody>
		  <% @users.each do |user| %>
		  <tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td>フォロー数：<%= user.follower.count %></td>
			<td>フォロワー数：<%= user.followed.count %></td>
			<% if current_user.following?(user) %>
			  <td><%= link_to "フォローを外す", unfollow_path(user.id), method: :POST %></td>
			<% else %>
			  <td><%= link_to "フォローする", follow_path(user.id), method: :POST %></td>
			<% end %>

			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		  </tr>
		  <% end %>
	    </tbody>
      </table>
    </div>
</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="row">

  <div class="col-xs-3">
    <h2>User info</h2>
    <%= render 'users/profile', user: @user %>

    <h2>New book</h2>
    <%= render 'books/newform', book: @book %>
  </div>

  <div class="col-xs-9">

    <h2>Books</h2>
    <table class="table table-hover table-inverse">
	  <thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	  </thead>
	  <tbody>
	    <% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td>コメント数:<%= book.book_comments.count %></td>
		</tr>
	    <% end %>
	  </tbody>
    </table>
  </div>
</div>

<div class="row">
  <% if @user.id == current_user.id %>
    <h2>Your MAP</h2>

   <script type="text/javascript">
      function initMap() {
      // #latitude,longitudeから位置を特定
        var test ={lat: <%= @user.latitude %>, lng: <%= @user.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
              });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @user.address %>';
        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });

        // #Map上の指定した位置にピンを挿して表示する
        var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
      }
    </script>

    <script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
    </script>

    <div id="map"></div>
  <% end %>
</div>