config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:show, :index, :edit, :update,]

  resources :books do
  	resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'

  get 'users/:id/followers' => 'relationships#followers', as: 'followers'
  get 'users/:id/follows' => 'relationships#follows', as: 'follows'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'

  get 'search' => 'search#search'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def self.search(search, word)
    	if search == "forward_match"
            @books = Book.where(['title LIKE ?', "#{word}%"])
        elsif search == "backward_match"
            @books = Book.where(['title LIKE ?', "%#{word}"])
        elsif search == "perfect_match"
            @books = Book.where(['title LIKE ?', "#{word}"])
        elsif search =="partial_match"
            @books = Book.where(['title LIKE ?', "%#{word}%"])
    	else
    		@books = Book.all
    	end
    end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_user, only: [:update, :edit]

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
    @book1 = Book.new
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all
    @book = Book.new
  end


  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
  		redirect_to @book, notice: "successfully created book!"
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def baria_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
    redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
<td><%= link_to(book.user) do %>
	  <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
	  <% end %></td>
<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
<td><%= book.body %></td>
  <% if book.favorited_by?(current_user) %>
    <td><%= link_to book_favorites_path(book),method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <% end %>
    <%= book.favorites.count %></td>
  <% else %>
    <td><%= link_to book_favorites_path(book), method: :post, remote: true do %>
	    <i class="fa fa-heart-o" aria-hidden="true"></i>
		<% end %>
		<%= book.favorites.count %></td>
  <% end %>
  <td>コメント数:<%= book.book_comments.count %></td>

app/views/books/_comments.html.erb
<table class="table">
  <% book.book_comments.each do |book_comments| %>
    <tr>
  	  <td>
  	  	<%= link_to (book_comments.user) do %>
	      <%= attachment_image_tag(book_comments.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
	    <% end %>
	    <%= book_comments.comment %>
	    <% if book_comments.user == current_user %>
	      <%= link_to "Destroy", book_book_comment_path(book_comments.book, book_comments),method: :delete, remote: true, class: "btn-sm btn-danger" %>
	    <% end %><br>
	    <%= book_comments.user.name %>
	  </td>
    </tr>
  <% end %>
</table>

<div>
  <%= form_with(model: [book, book_comment]) do |f| %>
  <%= f.text_area :comment, class:"col-xs-9" %>
  <%= f.submit "送信" %>
  <% end %>
</div>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
  	<% if book.errors.any? %>
		<% book.errors.full_messages.each do |message| %>
		<p>error</p>
		<%= message %>
		<% end %>
	<% end %>

	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_show.html.erb
<td><%= link_to (book.user) do %>
	<%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
	<%= book.user.name %>
	<% end %></td>
<td><%= link_to book.title, book %></td>
<td><%= book.body %></td>

	<% if book.user_id == current_user.id %>
	  <td><%= link_to "Edit",edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
	  <td><%= link_to "Destroy",book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book.id}" %></td>
	<% end %>

	<% if book.favorited_by?(current_user) %>
	  <td><%= link_to book_favorites_path(book),method: :delete, remote: true do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		<% end %>
		<%= book.favorites.count %></td>
	<% else %>
		<td><%= link_to book_favorites_path(book), method: :post, remote: true do %>
			<i class="fa fa-heart-o" aria-hidden="true"></i>
			<% end %>
			<%= book.favorites.count %></td>
	<% end %>
<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				  <tr class="book_<%= book.id %>">
				     <%= render 'books', book: book %>
			      </tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book1 %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr class="book_<%=@book.id%>">
					<%= render 'show', book: @book %>
				</tr>
		</table>

		<div class="comments_table">
			<%= render 'comments', book: @book, book_comment: @book_comment %>
		</div>
	</div>
</div>