config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:show, :index, :edit, :update,]

  resources :books do
  	resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'

  get 'users/:id/followers' => 'relationships#followers', as: 'followers'
  get 'users/:id/follows' => 'relationships#follows', as: 'follows'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'

  get 'search' => 'search#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script  src=
   "https://kit.fontawesome.com/5eecfabe72.js" crossorigin="anonymous"></script>
    <script  src=
    "https://kit.fontawesome.com/5eecfabe72.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <div class="container">
        <header class="navbar navbar-fixed-top navbar-inverse">
            <nav class="nav navbar-nav navbar-left">
              <span>Bookers</span>
            </nav>
            <nav>
              <ul class="nav navbar-nav navbar-right">
              <!--if文でサインインとアウト時の表示を変更-->
                <% if user_signed_in? %>
                  <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
                  <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
                  <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
                  <li><%= link_to ' logout', destroy_user_session_path, method: :delete, data: { turbolinks: false },  class: 'glyphicon glyphicon-log-out logout' %></li>
                <% else %>
                  <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
                  <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
                  <li><%= link_to ' sign up', new_user_registration_path, data: { turbolinks: false }, class: 'glyphicon glyphicon-edit sign_up' %></li>
                  <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
                <% end %>
              </ul>
            </nav>
        </header>

            <div class="search">
              <% if user_signed_in? %>
                <%= form_tag(search_path,:method => 'get') do %>
                <%= text_field_tag :word %>
                <%= select_tag 'range',options_for_select(([["user","1"],["book","2"]])) %>
                <%= select_tag 'search', options_for_select([["前方一致","forward_match"],["後方一致","backward_match"],["完全一致","perfect_match"],["部分一致","partial_match"]]) %>
                <%= submit_tag '検索' %>
                <% end %>
              <% end %>
            </div>
    </div>
    <!--ヘッダーの記述-->

    <div class="container">
      <p id="notice" style="padding-top: 20px;"><%= notice %></p>
       <!--デバイスでnotice設定されているので呼び出してるだけ-->
      <%= yield %>
    </div>
  </body>
</html>